### PR TITLE
Publish v6.3.0

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- Publish v6.3.0

### CODE REVIEW

**Comment by huayunh** [comment]
Does this feel like a high-priority bug to you? 

https://github.com/pxblue/angular-themes/issues/29

**Comment by daileytj** [comment]
> Does this feel like a high-priority bug to you?
> 
> #29

This was just a showcase issue and it has been fixed and merged.

**Review by daileytj — APPROVED** [review]
Approved. Will need to update the release date in the changelog before merging.

**Review by jeffvg — APPROVED** [review]
looks good

**Pull request merged**
